flask_restful/fields.py, tests/test_fields.py
I cherry-picked the relevant commits from #316 and resolved the merge conflicts.
=> Fixed fields.Url to allow it to be used with blueprints

flask_restful/reqparse.py, tests/test_reqparse.py
This should resolve #279. Unsure if it's worth it at this point with #335 under consideration, but it makes the current behavior more consistent and predictable.
=> Allow user to use validators for upladed files

docs/installation.rst
This may not be the best first pull request but just thought maybe this needed to be updated. Let me know what you think :)
=> Update git clone url from twilio to flask-restful

AUTHORS.md, CHANGES.md, setup.py
=> Release 0.3.2

flask_restful/fields.py, tests/test_fields.py
Made list sub-fields work with classes (previously only worked with dicts)
=> Made list fields work with classes

flask_restful/inputs.py, tests/test_inputs.py
=> Remove min. year limit 1900 in inputs date func

AUTHORS.md, CHANGES.md
I think this just about covers it. Anything else you want to add to this release, @joshfriend?
=> Prepare 0.3.3 release

flask_restful/inputs.py, tests/test_inputs.py
Maybe i don't understand something, but looks like current int_range input doesn't work. So it's a fix.
=> fix int_range input

flask_restful/__init__.py, flask_restful/utils/__init__.py, tests/test_api.py
Fixes #205 removed status code from handle_error response and used description as message content if present
=> Removed exception swallowing in handle_error

docs/fields.rst
This is a great feature, and it is not mentioned anywhere in the docs.
=> Added documentation about nested attribute access

flask_restful/__init__.py
Here is the related issue: https://github.com/mitsuhiko/flask/issues/1477
=> Fixed a regression introduced by Flask 1.0

flask_restful/__init__.py, tests/test_api.py
=> Forward the HTTPException headers

tests/test_api.py
=> Fix typo in test api

AUTHORS.md, CHANGES.md, setup.py
=> Release 0.3.5

flask_restful/__init__.py
Wasted a few seconds wondering why there is no new line between those params so I decided to add one :)
=> Add missing new line

setup.py
I included this fix in #616, but I figured I'd break it out for a quick and easy fix.
=> Fix CI Error for Python 3.x

docs/extending.rst, flask_restful/__init__.py, tests/test_api.py
=> Extend method decorators

docs/intermediate-usage.rst
`__init__() takes 0 positional arguments but 1 was given`
=> DOCS: fix missing `self` in ctor

README.md
Fixes #663 issue to link in readme
=> fixing link to readme source

.travis.yml
Added container-based virtualization and additional python targets (3.6, pypy, pypy3) to Travis config.
=> Test against Flask 0.10 and Flask 0.12;  test py3.6/pypy

flask_restful/reqparse.py
https://github.com/flask-restful/flask-restful/issues/721
=> use custom error code for parse_args

docs/extending.rst
Fix typo serializtion -> serialization
=> Fix typo in docs/extending

flask_restful/__init__.py
Resolving issue [717](https://github.com/flask-restful/flask-restful/issues/717).
=> Change type-hint

.travis.yml, flask_restful/__init__.py, flask_restful/reqparse.py, flask_restful/utils/__init__.py, setup.py
=> Add python 3.8 support.

tests/test_accept.py, tests/test_api.py, tests/test_cors.py
reduce usage of nose tools (assert_equals / true / false) unless its really needed
=> port nose tools

tests/test_api.py, tests/test_api_with_blueprint.py, tests/test_fields.py, tests/test_reqparse.py
sed -i 's/assertEquals/assertEqual/' tests/*.py
reduces runtime deprecation warnings
=> test upgrades
