flask-restful/flask-restful

flask_restful/fields.py, flask_restful/inputs.py, tests/test_fields.py, tests/test_inputs.py
Also fixes forced conversion to UTC as noted by @ianozsvald [here](https://github.com/flask-restful/flask-restful/issues/368#issuecomment-69040032)
=> Fix truncation of microseconds in iso8601 date inputs

flask_restful/reqparse.py, tests/test_reqparse.py
#159 introduced a bug where the following happens:
```python
parser = RequestParser()
parser.add_argument('name')
```
```
POST /foo {"name": null}
```
```python
args = parser.parse_args()
{'name': 'None'}
```
There was (is) a check for skipping a cast to a string if the input is string but the value in the `request` is `None` [here](https://github.com/flask-restful/flask-restful/blob/0.3.1/flask_restful/reqparse.py#L107-L109), but 442db82 altered the default `type` of `Argument` such that it no longer works:
```python
>>> import six, inspect
>>> value = None
>>> arg_type = six.text_type
>>> value is None and inspect.isclass(arg_type) and issubclass(arg_type, six.string_types)
True
>>> arg_type = lambda x: six.text_type(x)
>>> s is None and inspect.isclass(arg_type) and …
```
=> String arguments parsing `null` from JSON as string "None"

flask_restful/__init__.py, tests/test_api.py
Fixes #396
Example:
```python
from flask import Flask, Blueprint
from flask.ext.restful import Api, Resource, url_for
app = Flask(__name__)
api_bp = Blueprint('api', __name__)
api = Api(api_bp, prefix='/api')
class PersonApi(Resource):
def get(self, uuid=None):
return api.url_for(PersonApi, uuid=uuid)
api.add_resource(PersonApi, '/persons/<string:uuid>', endpoint='persons_ep')
app.register_blueprint(api_bp)
if __name__ == '__main__':
app.run(debug=True)
```
@mjmare / @systemkeeper could you test this fix with your applications by `pip install`-ing or adding `git+https://github.com/flask-restful/flask-restful.git@72afe1aba68a61dba0c84d180364c9d2fd50fbd6` to your `requirements.txt`?
=> Fix url_for when used with Blueprints 

flask_restful/utils/cors.py, tests/test_cors.py
The "Access-Control-Expose-Headers" header lets a server whitelist headers that browsers are allowed to access.
=> add CORS "Access-Control-Expose-Headers" support

flask_restful/reqparse.py
parse_args method directly referenced the Argument class instead of
using the instance variable argument_class. Replaced the Argument
class with the instance variable.
copy method directly referenced RequestParser class instead of
using self.__class__ such that if RequestParser had been
subclassed that would have been lost if the copy method was
used. Replaced RequestParser reference within copy method to
leverage self.__class__.
=> [BUGFIX] Fix class references in RequestParser

flask_restful/fields.py, tests/test_fields.py
Is there any reason that the `inspect.isfunction` is being used instead of the `callable()` builtin? This small patch allows people to use any callable, in my use case partial functions.
=> Allow any callables to be used as lazy attributes.

flask_restful/reqparse.py, tests/test_reqparse.py
Thanks for feedback, improved the shortcomings and responded to your comments:
https://github.com/flask-restful/flask-restful/pull/427/files#r28646182
I would really like to be able to set the trimming on RequestParser level. The reason is that for back-ends that handle form submissions, a whitespace can be submitted on any input field. In an ideal world trimming could be configured on an application level, however that's too much asked for now :)
=> Trim support with fixes

docs/intermediate-usage.rst, flask_restful/reqparse.py
Both the `intermediate usage` example on custom types and the related docstrings in the `Argument` class are quite confussing for newcomers:
- Returning an actual value instead of `True` draws a clearer picture of the expected behaviour one custom type.
- Both the `email` example function and the `Argument` docstring reference a `ValidationError` exception which is not present on source and is actually not required (any raised exception will do for converting/validating types).
=> Fix custom type docs on "Intermediate usage" and docstring

flask_restful/inputs.py
If you will try co copy regex input, you will get an error:
```
TypeError: cannot deepcopy this pattern object
```
=> Fixed problem with deepcopy

flask_restful/__init__.py
This is a modification of https://github.com/flask-restful/flask-restful/pull/111
The problem with the hasattr check is that it forces an arbitrary restriction on the types of exceptions that can be thrown - The exception (or any base class) cannot have an attribute named 'code'. In practice this leads to a very confusing flow where some exceptions appear to work properly but not others. I personally spent a lot of time pulling my hair trying to figure out why one particular exception wasn't working properly in our system.
My belief (would be great if someone could confirm) is that the original goal was to catch werkzeug exceptions and handle them.
http://werkzeug.pocoo.org/docs/0.10/exceptions/#baseclass
So this change makes an explicit instance check against HTTPException rather than …
=> Explicitly check the class type for propagate_exceptions 

flask_restful/__init__.py, tests/test_api.py
Boto's [JSONReponseError](http://boto.readthedocs.org/en/latest/ref/boto.html#boto.exception.JSONResponseError) provides an attribute `code`, which makes Flask Restful break in the event that is the exception. This adds some very basic type checking to make sure that the real error isn't hidden.
```
Traceback (most recent call last):
File "/Users/newmaniese/VirtualEnvs/bobcat2/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "/Users/newmaniese/VirtualEnvs/bobcat2/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/Users/newmaniese/VirtualEnvs/bobcat2/src/flaskrestful/flask_restful/__init__.py", line 261, in error_router
return …
```
=> Check if the code is a proper integer before comparison

AUTHORS.md, flask_restful/representations/json.py, tests/test_api.py
See: #292, #373 
Allow users to set a `RESTFUL_JSON` dictionary in the application configuration to pull settings from rather than pulling them from a global dictionary. Additionally, a new line is *always* appended to JSON representations See mitsuhiko/flask#1262 for details on this issue. 
I couldn't get tox to build a 3.3 environment, but all tests should pass with it.
=> Pull json.dumps settings from application configuration

setup.py
will stop flask-restful from appearing as a blocker on https://caniusepython3.com 
(these are the ones tested in Travis)
=> add trove classifiers

CHANGES.md, flask_restful/__init__.py
It's not always desirable to log the exception traceback and by changing this mechanism to use Flask's own ``log_exception(e)`` method, it's much easier to change this behavior.
=> For HTTP codes 500 and over, use app object's exception logger

flask_restful/fields.py, flask_restful/inputs.py
Use isinstance where possible instead of type
Note: There is one scenario where running isinstance results in incorrect logic: In the file, fields.py, under class List, there is a condition check 'not type(self.container) is Raw' [line 191](https://github.com/flask-restful/flask-restful/blob/master/flask_restful/fields.py#L191). In this case using 'not isinstance(self.container, Raw' would be incorrect because 'isinstance(self.container, Raw)' returns True (because of inheritance), while 'type(self.container) is Raw' returns False
=> Replace type checking using type with isinstance where possible

docs/reqparse.rst, flask_restful/reqparse.py, tests/test_reqparse.py
`Argument.help` can now completely control the error message returned in the response via the `{error_msg}` interpolation token. This addresses issue #514.
See the updated docs for more details.
=> Changed how Argument.help is formatted in response

flask_restful/__init__.py, tests/test_accept.py
Add test for matching the any \*/\* mime type when multiple representations are active
prevent a representation to be picked at semi-random due to the unspecified order of elements in a dict
The test that I added fails with the current flask-restful master. Not every single time, but.. run the test 3/4 times and you should see the problem.
=> Fix representation being picked at random

docs/intermediate-usage.rst
Add missing 'r' at `required` arguement
=> Fix typo in example

docs/fields.rst
This ensures the following code block gets formatted correctly.
=> Fixed code block formatting

flask_restful/reqparse.py, tests/test_reqparse.py
addresses bug in #508 
here the problematic code:
error_str = six.text_type(error)
error_msg = self.help.format(error_msg=error_str) if self.help else error_str
msg = {self.name: "{0}".format(error_msg)}
six.text_type is unicode in python 2.x
`>>> six.text_type`
`>>> <type 'unicode'>`
The help string should be unicode if you rely on the new error message formatting, and you expect to send unicode strings
`error_msg = self.help.format(error_msg=error_str) if self.help else error_str`
The message was coerced into byte string, no matter if the actual error is unicode.
`msg = {self.name: u"{0}".format(error_msg)}`
=> new Argument.help supports unicode error messages

README.md, docs/reqparse.rst
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
=> Convert readthedocs links for their .org -> .io migration for hosted projects

docs/extending.rst
Corrected `api = restful.Api(app)` to `api=Api(app)` in the 0.3.5 docs.
=> Fix for Issue # 603: Wrong/Deprecated usage in 0.3.5 docs

tox.ini
Added latest stable version of python (3.5) to the tox file, confirmed all tests pass on this version. Also added py36, even though it isn't available yet in Travis.
=> Add python 3.5 and 3.6 support to tox

flask_restful/__init__.py
As Blueprints are supported for flask-restful api creation, adding blueprint to ':type' in doc string
=> __init__.py update for Api class docs string to support Blueprints

flask_restful/reqparse.py, tests/test_reqparse.py
This fix an issue when parsing a list value inside body data (JSON).
Value returned by `source.get(name)` can already be a list provided inside JSON data, so it should not be wrapped into another list in this case. The value should be used as is if it's already a sequence.
=> Fix reqparse (action='append' and location='json')

docs/reqparse.rst
The last paragraph is not setting a proper formatting to the code block.
=> Fix formatting error in reqparse.tst

flask_restful/representations/json.py, flask_restful/utils/__init__.py
It's a simple work around to key sorting under Python 3.  
Related issue: #678
=> turn off key sorting of json response in python3

flask_restful/__init__.py, tests/test_api.py
This PR attempts to fix issue #685. Python 3 doesn't allow comparisons of different types (e.g. None > int).
=> BugFix for python3 error handling

flask_restful/__init__.py
The current notation (specifying :type twice) is non-standard and causes linters/IDEs to pick up the lowest one. This is incorrect.
In python 2 and 3 or logic is the most standard, so I'm updating to that for backwards compatibility.
In python 3 Union[int, float] is the standard.
=> Should use or logic for :type, Union for python 3

docs/conf.py
This is a (possible) fix for the breakage of `conf.py` when building documentation on ReadTheDocs.org.
=> Fix Import Error in conf.py on ReadTheDocs.org

docs/quickstart.rst
i find a unused import module when i read the docs, may be it can delete, right?
=> delete unused import

docs/installation.rst
According to tox.ini py35 and py36 are supported or is there anything else that needs to be done to enable the support?
=> Include latest python version in installation.rst

README.md
Download count is not supported anymore. It was broken for a long period of time, but now it was completely removed.
That's how it looks right now:
So, I have removed this badge.
=> Removes download count

tests/test_api.py
This is fixed:
```
Traceback (most recent call last):
File "/builddir/build/BUILD/flask-restful-0.3.6/tests/test_api.py", line 787, in test_fr_405
set(['HEAD', 'OPTIONS'] + HelloWorld.methods))
TypeError: can only concatenate list (not "set") to list
```
=> test_api: fix traceback

tests/test_api.py
Just a bug I caught while reading through the test code.
Changed `WWW-Autheneticate` to `WWW-Authenticate`
=> Typo in test

tests/test_api.py
The current test expect the response to not contain 'WWW-Authenticate' in the header, while this header is required. This change removes the test case. 
> The WWW-Authenticate response-header field MUST be included in 401 (Unauthorized) response messages.
[Reference](https://tools.ietf.org/html/rfc2616#section-14.47)
=> Remove test_handle_error_401_no_challenge_by_default Fix #811

flask_restful/__init__.py, tests/test_api.py
Side effect: if e.response is not None, error messages and other information stored in e: HTTPException may be overridden.
=> Fix overridden response when calling abort with Response; Resolves #791

docs/extending.rst
Updating docs to include a line about Custom Error Messages, requiring that the exception has  `HTTPException` as the parent.
=> add note about custom exceptions

docs/fields.rst
Corrected code snippet to valid syntax for usage of copy and pasting
=> fix field snippet

flask_restful/reqparse.py, tests/test_reqparse.py
When special-casing the request parser for Decimal, passing the name of the field as the second argument is incorrect:
```python
try:
if self.type is decimal.Decimal:
return self.type(str(value)) .   # <--- Incorrect second parameter, can never work in py3
else:
return self.type(value, self.name)
except TypeError:
return self.type(value) # <--- Fallback, but without string conversion
```
The second argument of Decimal is a context. Python 3 checks this is, in fact, a context, whereas Python 2 ignores it if not needed. This means in Python 3 that special-case line is never successful, so it is handled below. However, there is a difference: the first converts to string, the second does not. This results in different values of Decimal being parsed:
```python
>>> import decimal
>>> value = …
```
=> Fix wrongly parsed Decimal fields

CHANGES.md, flask_restful/__version__.py
After The conversation with @joshfriend  in #855 I took a look at the repo and figured the changes already in master after the last release v0.3.7, even the python 3.8 support alone, could potentially warrant a new release, even if there are other issues and PRs pending.
To aid with that, I have prepared the CHENGES.md file, although it needs a final modification if and when this gets accepted (the date).
Side note: The solution proposed in #855 (Installing from git, pinning one commit) does not work in environments where a pypi cache such as Artifactory or Nexus is in place.
=> Proposed v0.3.8 release

flask_restful/inputs.py
Eliminate potential confusion when attempting to parse dates with
`datetime_from_iso8601`, ex:
https://bitbucket.org/nielsenb/aniso8601/issues/25/parse_datetime-cannot-handle-missing-time
=> Make it explicit that datetime_from_iso8601 parses datetimes.

flask_restful/__init__.py
Closes #912 
Based on input from  #913
The referenced PR worked for me, but this removes the private import - the fundamental difference will be the lack of an assert.
```
def _endpoint_from_view_func(view_func):
"""Internal helper that returns the default endpoint for a given
function.  This always is the function name.
"""
assert view_func is not None, "expected view func if endpoint is not provided."
return view_func.__name__
```
Happy to close if #913 is updated to address this!
=> Remove private import for flask 2.0 compatability

flask_restful/__init__.py, tests/test_api.py
Flasks `app.propagate_exceptions` will be deprecated in the next release, and although the Flask developers don't have a release date, given their release history it may be sooner rather than later. If it is deprecated Flask-RESTful will throw an exception in `flask_restul.__init__` in the handle_errors method. This is the only place in Flask-RESTful where this
attribute is accessed.
This pull request addresses the need to fix this issue in Flask-RESTful. Along with the fix I cleaned up that area of the code a bit, and made a few minor style changes, e.g., fixing a typo, removing an extra line feed, etc. Unit tests were added and pass. 
Currently in Flask, if `app.propagate_exceptions` is set to True then the exceptions are re-raised rather than being handled by the app’s error handlers. …
=> Flask-RESTful will fail when Flask deprecates propagate_exceptions: Fix
